
on:
  schedule:
    - cron: 22 4 * * *
  workflow_dispatch:

jobs:
  update-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install deps
        run: pip install -r requirements.txt

      - run: python inspect_all_latest.py

      - name: Commit and push

        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "update-latest"
            git push
          else
            echo "No changes"
          fi
